### ISSUE TITLE
MATLAB setenv/getenv does not play nice with YARP's NetworkBase::getEnvironment 	

### ISSUE THREAD

**Issue by traversaro** [robotology-playground/WBI-Toolbox-controllers#28] opened 2016-06-07 15:03 UTC
[`NetworkBase::getEnvironment`](http://www.yarp.it/classyarp_1_1os_1_1NetworkBase.html#a283af07d20c62b6eb9826f9bda68c3f2)

**Comment by gabrielenava** [comment] 2017-10-06 08:50
Closing as a duplicate of https://github.com/robotology-playground/WBI-Toolbox-controllers/issues/27

**Closed as completed by gabrielenava** 2017-10-06 08:50 UTC
